---
title: "Leaguepedia"
author: "Jasen"
date: "2023-07-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(hrbrthemes)
```



```{r}
# player csv

player <- read.csv('player.csv')

# tournaments 

relevant_leagues <- c('LoL The Champions', 'Europe League Championship Series', 'LoL Champions Korea', 'League of Legends Championship Series', 'LoL EMEA Championship', 'Tencent LoL Pro League', 'North America League Championship Series')


tournaments <- read.csv('tournaments.csv')
tournaments2 <- tournaments %>% 
  filter(League %in% relevant_leagues) %>% 
  filter(!is.na(SplitNumber)) %>% 
  arrange(League) %>% 
  filter(StandardName != '')

# remove playoffs/qualifiers rows

temp_tourney_name <- tournaments2$Name

is_playoffs <- grepl('Playoffs', temp_tourney_name, fixed = TRUE)
is_qualifiers <- grepl('Qualifiers', temp_tourney_name, fixed = TRUE)
is_groups <- grepl('Groups', temp_tourney_name, fixed = TRUE)
is_championship <- grepl('Championship', temp_tourney_name, fixed = TRUE)
is_lockin <- grepl('Lock', temp_tourney_name, fixed = TRUE)
is_showdown <- grepl('Showdown', temp_tourney_name, fixed = TRUE)
is_finals <- grepl('Finals', temp_tourney_name, fixed = TRUE)

should_remove <- is_playoffs | is_qualifiers | is_groups | is_championship | is_lockin | is_showdown | is_finals

tournaments3 <- tournaments2[!should_remove,]

relevant_leagues <- tournaments3$Name

```


```{r}
# tournament players

 

modify_tp_data <- function(csv_name){
  tp <- read.csv(csv_name)

  should_remove <- rep(F, nrow(tp))
  
  temp <- tp$OverviewPage
  
  bad_words <- c('Thailand', 'Playoffs', 'Qualifier', 'Championship', 'Lock', 'Showdown', 'Promotion', 'Finals', 'Expansion', 'Showmatch', 'Proving', 'Electronic', 'Telecom', 'Selecter', 'Academy', 'CL/', 'Rivals', 'All-Star', 'Online', 'WellPlayed', 'LPLOL', 'Azubu', 'CBLOL', 'Streamathon', 'Alienware', 'Ascending', 'CEVO', 'Dawn', 'Forge', 'Arabian', 'KCON', 'League of Champions', 'Lenovo', 'India', 'Orange', 'Risen', 'SquareOne', 'UCC', 'Preseason')
  for(i in bad_words){
    temp_remove <- grepl(i, temp, fixed = TRUE)
    should_remove <- should_remove | temp_remove
  }
  
  tp2 <- tp[!should_remove,] 
  
  
  tp3 <- tp2  %>% arrange(OverviewPage, Team, `N.PlayerInTeam`)
  
  # remove coaches
  
  temp_roles <- tp3$Role
  has_coach <- grepl('Coach', temp_roles, fixed = TRUE)
  
  tp4 <- tp3[!has_coach,]
  
  tp4
}

tp_lcs <- modify_tp_data('tournament_players_LCS.csv')
tp_lec <- modify_tp_data('tournament_players_LEC.csv')
tp_lck <- modify_tp_data('tournament_players_LCK.csv')
tp_lpl <- modify_tp_data('tournament_players_LPL.csv')
tp_champions <- modify_tp_data('tournament_players_Champions.csv')

tp_total <- rbind(tp_lcs, 
                  tp_lec,
                  tp_lck,
                  tp_lpl,
                  tp_champions)
```

```{r}
# tournament rosters

tr <- read.csv('tournament_rosters.csv') %>% 
  filter(Tournament %in% relevant_leagues)
```


# 5) Join tp (tournament_players) with players (df with birthday info)

```{r}
temp <- player %>% select('Birthdate', 'AllName', 'Name')
colnames(temp) <- c('Birthdate', 'Player', 'Name')
players_with_dob <- tp_total %>% left_join(temp, by = 'Player')
```

# 5.5) extract team name

```{r}
wow <- players_with_dob$PageAndTeam
list_of_teams <- c()

for(i in 1:length(wow)){
  temp <- unlist(strsplit(wow[i], "_"))
  temp2 <- temp[length(temp)]
  list_of_teams <- c(list_of_teams, temp2)
}

players_with_dob <- players_with_dob %>% mutate(Team = list_of_teams)
```

# 5.6) extract league name

```{r warning=FALSE}
wow <- players_with_dob$OverviewPage

leagues <- c()
season_orders <- c()
years <- c()
seasons <- c()
regions <- c()

for(i in 1:length(wow)){
  league_name <- wow[i]
  
  # retrieve season
  
  if(grepl('Winter', league_name, fixed = TRUE)){
    season <- 'Winter'
  } else if(grepl('Spring', league_name, fixed = TRUE)){
    season <- 'Spring'
  } else if(grepl('Summer', league_name, fixed = TRUE)){
    season <- 'Summer'
  } else{
    season <- 'N/A'
    #print(league_name)
  }
  
  # retrieve region
  
  if(grepl('Champions', league_name, fixed = TRUE) | grepl('LCK', league_name, fixed = TRUE)){
    region <- 'LCK'
  } else if(grepl('LPL', league_name, fixed = TRUE)){
    region <- 'LPL'
  } else if(grepl(c('LEC'), league_name, fixed = TRUE) | grepl('EU', league_name, fixed = TRUE)){
    region <- 'LEC'
  } else if(grepl('LCS', league_name, fixed = TRUE)){
    region <- 'LCS'
  } else{
    region <- 'N/A'
    print(league_name)
  }
  
  # retrieve year
  
  if(grepl('Season 3', league_name, fixed = TRUE)){
    temp_year <- '2013'
  } else{
    start_index <- unlist(gregexpr('2', league_name))[1]
    # if(is.na(start_index)){
    #   print(league_name)
    # }
    end_index <- start_index + 3
    
    temp_year <- substr(league_name, start_index, end_index)
  }
  
  years <- c(years, temp_year)
  seasons <- c(seasons, season)
  regions <- c(regions, region)
  
  league <- paste(region, temp_year, sep = ' ')
  league <- paste(league, season, sep = ' ')
  leagues <- c(leagues, league)
  
  season_order <- paste(temp_year, season)
  season_orders <- c(season_orders, season_order)
}

players_with_dob <- players_with_dob %>% mutate(league_name = leagues) %>%
  mutate(season_order = season_orders) %>%
  mutate(year = as.numeric(years)) %>% 
  mutate(season = as.factor(seasons)) %>% 
  mutate(region = as.factor(regions))
```

# 6) Find the leagues and their start dates

```{r}
tourney_start_date <- tournaments3 %>% select('DateStart', 'Name')

wow <- tourney_start_date$Name

leagues <- c()

for(i in 1:length(wow)){
  league_name <- wow[i]
  
  # retrieve season
  
  if(grepl('Winter', league_name, fixed = TRUE)){
    season <- 'Winter'
  } else if(grepl('Spring', league_name, fixed = TRUE)){
    season <- 'Spring'
  } else if(grepl('Summer', league_name, fixed = TRUE)){
    season <- 'Summer'
  } else{
    season <- 'N/A'
    #print(league_name)
  }
  
  # retrieve region
  
  if(grepl('Champions', league_name, fixed = TRUE) | grepl('LCK', league_name, fixed = TRUE)){
    region <- 'LCK'
  } else if(grepl('LPL', league_name, fixed = TRUE)){
    region <- 'LPL'
  } else if(grepl(c('LEC'), league_name, fixed = TRUE) | grepl('EU', league_name, fixed = TRUE)){
    region <- 'LEC'
  } else if(grepl('LCS', league_name, fixed = TRUE)){
    region <- 'LCS'
  } else{
    region <- 'N/A'
    print(league_name)
  }
  
  # retrieve year
  
  if(grepl('Season 3', league_name, fixed = TRUE)){
    temp_year <- '2013'
  } else{
    start_index <- unlist(gregexpr('2', league_name))[1]

    end_index <- start_index + 3
    
    temp_year <- substr(league_name, start_index, end_index)
  }
  
  years <- c(years, temp_year)
  
  league <- paste(region, temp_year, sep = ' ')
  league <- paste(league, season, sep = ' ')
  
  if(league == 'LCS NA Spring'){
    print(league_name)
  }
  
  leagues <- c(leagues, league)
}
tourney_start_date <- tourney_start_date %>% mutate(league_name = leagues)
```

# 7) merging tournament start date with player dob

```{r}
temp <- tourney_start_date %>% select(- 'Name')

#players_3 <- players_with_dob %>% left_join(temp, by = league_name)

players_with_dob_2 <- players_with_dob %>% filter(league_name %in% temp$league_name)

leagues <- players_with_dob$league_name
date_starts <- c()
for(i in 1:length(leagues)){
  the_date_vec <- temp %>% filter(league_name == as.name(leagues[i]))

  the_date <- the_date_vec$DateStart

  
  date_starts <- c(date_starts, the_date)
  
  if(i %% 100 == 0){
    print(i)
  }
  
}

players_3 <- players_with_dob_2 %>% mutate(start_date = date_starts)

wow <- as.Date(players_3$Birthdate)
wow2 <- as.Date(players_3$start_date)

diff_years <- as.numeric(wow2 - wow)/365.25

players_3 <- players_3 %>% mutate(age_at_start = diff_years)

players_4 <- players_3 %>% select('Team', 'Player', 'league_name', 'Birthdate', 'start_date', 'age_at_start', 'season_order', 'region', 'year', 'season')
```

# CALCULATE AVERAGE AGE FOR EACH LEAGUE

```{r}
average_age <- players_4 %>% 
  group_by(league_name) %>%
  summarise(across(age_at_start, mean, na.rm = TRUE))

the_leagues <- c()
the_seasons <- c()

for(i in 1:nrow(average_age)){
  temp <- average_age$league_name[i]
  the_league <- substr(temp,1,3)
  length_of_name <- nchar(temp)
  the_season <- substr(temp, 5, length_of_name)
  
  the_leagues <- c(the_leagues, the_league)
  the_seasons <- c(the_seasons, the_season)
}

average_age <- average_age %>% mutate(league = factor(the_leagues)) %>% 
  mutate(season_order = the_seasons)


```

# graph

```{r}
split_scores <- c()
year_dict <- c(1,4,7,9,11,13,15,17,19,21,23,26)
temp_season_vec <- average_age$season_order
for(i in 1:nrow(average_age)){
  temp_season_2 <- temp_season_vec[i]
  temp_length <- nchar(temp_season_2)
  temp_year <- as.numeric(substr(temp_season_2,1,4))
  temp_season <- substr(temp_season_2, 6, temp_length)
  
  year_index <- temp_year - 2011
  if(temp_season == 'Winter'){
    season_index <- -1
  } else if(temp_season == 'Spring'){
    season_index <- 0
  } else if(temp_season == 'Summer'){
    season_index <- 1
  } else{
    print('WTFFFFF')
  }
  
  split_score <- year_dict[year_index] + season_index
  split_scores <- c(split_scores, split_score)
}

average_age$split_order <- split_scores

splits_in_order <- average_age %>% arrange(split_order)

splits_in_order_2 <- unique(splits_in_order$season_order)
```

```{r}
g <- ggplot() + geom_point(aes(x = split_order, y = age_at_start, color = league), data = average_age) +
  geom_line(aes(x = split_order, y = age_at_start, color = league), data = average_age) +
  ylab('Average Age') + 
  scale_x_discrete(name ="Split", 
                    limits=splits_in_order_2) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.3)) + 
  ylim(19,25) +
  annotate('rect', xmin=0.5, xmax=2.5, ymin=19, ymax=25, alpha=.1, fill='black')  +
  annotate('rect', xmin=5.5, xmax=8.5, ymin=19, ymax=25, alpha=.1, fill='black')  +
  annotate('rect', xmin=10.5, xmax=12.5, ymin=19, ymax=25, alpha=.1, fill='black')  +
  annotate('rect', xmin=14.5, xmax=16.5, ymin=19, ymax=25, alpha=.1, fill='black')  +
  annotate('rect', xmin=18.5, xmax=20.5, ymin=19, ymax=25, alpha=.1, fill='black')  +
  annotate('rect', xmin=22.5, xmax=24.5, ymin=19, ymax=25, alpha=.1, fill='black') +
  scale_y_continuous(breaks=seq(0,40,1)) +
  scale_color_manual(values = c("LCS" = "darkorchid2",
                                "LEC" = "green2",
                                "LPL" = "red2",
                                "LCK" = "royalblue2")) +
  guides(color = guide_legend(title = "Region"))



pdf('age_graph.pdf')
g
dev.off()
```

# age distribution in 2023 summer

```{r}
set.seed(125)
players_2023_summer <- players_4 %>% filter(season_order == '2023 Summer') %>% 
  distinct()

g_summer_2023 <- ggplot() + 
  geom_boxplot(aes(x=reorder(region, age_at_start,na.rm = TRUE), y=age_at_start, color = region, fill = region), outlier.shape = NA, data = players_2023_summer) +
  geom_jitter(aes(x=region, y=age_at_start), data = players_2023_summer, size=0.8, width = 0.3) + 
  scale_y_continuous(breaks=seq(0,40,1)) +
  scale_fill_manual(values = c("LCS" = "darkorchid2",
                            "LEC" = "green2",
                            "LPL" = "red2",
                            "LCK" = "royalblue2")) +
  scale_color_manual(values = c("LCS" = "gray50",
                          "LEC" = "gray50",
                          "LPL" = "gray50",
                          "LCK" = "gray50")) +
  
  # theme_ipsum() +

  ylab('Age') + 
  xlab('Region') + 
  theme(legend.position="none")

pdf('age_graph_2023_summer.pdf')
g_summer_2023
dev.off()
```

# youngest players

```{r}
wow <- players_2023_summer %>% select('Team', 'Player', 'age_at_start') %>% 
  mutate(age_at_start = round(age_at_start, 1))

head(arrange(wow, age_at_start), 20)

```

# oldest players

```{r}
head(arrange(wow, desc(age_at_start)), 20)
```



```{r}
```